<?php
return [
    'wedstrijden_titel' => 'Wedstrijden',
    'wedstrijden_discription' => 'Ontdek hier alle wedstrijden van afgelopen maanden of die nog moeten plaatsvinden.',
    'wedstrijd' => 'wedstrijd',
    'nieuws_titel' => 'Nieuwsartikelen',
    'nieuws_discription' => 'Overzicht van nieuwsartikelen',
    'nieuws_titel_artikel'=>'Artikel',
    'trainers_titel' => 'Gids',
    'trainers_discription' => 'Overzicht van alle gidsen',
    'tutorial_titel' => 'Tutorial & lessen',
    'tutorial_discription' => 'overzicht van lessen',
    'viePlaats_titel'=>'Visplaats',
    'trainer_titel'=>'Gids',
    'locatie'=>'Locatie',
    'locatie_description'=>'Kies locatie die het best past',
    'invulen'=>'Vul het formulier in',
    'overOns'=>'Over Ons',
    'overOns_description'=>'Lees hier hoe Fishing Friends jou hengelsport kan verrijken',
    'contact'=>'Contact',
    'contact_description'=>'Vul formulier in om ons te contacteren',
    'faq'=>'FAQ',
    'faq_description'=>'Meest voorkomende vragen',
    'faq_toevoegen'=>'Voeg nieuw faq toe',
    'update'=>'Aanpassen',
    'update_faq'=>'Pas het faq aan',
    'tutorial_titel_short'=>'tutorial & ',
    'dashboard'=>'Dashboard',
    'dahboard_description'=>'In deze sectie vind u een overzicht van uw activiteiten op de website',
]
?>