<?php
return [
    'wedstrijden_titel' => 'wedstrijden',
    'wedstrijden_discription' => 'Overzicht pagina van de wedstrijden',
    'wedstrijd' => 'wedstrijd',
    'nieuws_titel' => 'nieuws Artikelen',
    'nieuws_discription' => 'Overzicht van nieuws artikelen',
    'nieuws_titel_artikel'=>'Artikel',
    'trainers_titel' => 'Trainer & Gids',
    'trainers_discription' => 'Overzicht van alle gidsen',
    'tutorial_titel' => 'Tutorial & lessen',
    'tutorial_discription' => 'overzicht van lessen',
    'viePlaats_titel'=>'Vis plaats',
    'trainer_titel'=>'Trainer',
    'locatie'=>'Locatie',
    'locatie_description'=>'Kies Locaite die best past',
    'invulen'=>'Vul de formulier in',
    'overOns'=>'Over Ons',
    'overOns_description'=>'Hier vind je overzicht over ons',
    'contact'=>'Contact',
    'contact_description'=>'Vul formulier in om ons te contacteren',
    'faq'=>'FAQ',
    'faq_description'=>'Meest voorkomende vragen',
    'faq_toevoegen'=>'Voeg nieuw faq toe',
    'update'=>'Aanpasen',
    'update_faq'=>'Pas het faq aan',
    'tutorial_titel_short'=>'tutorial & ',
    'dashboard'=>'Dashboard',
    'dahboard_description'=>'In deze sectie vind u overzicht van u activiteiten op de website',
]
?>